export const gameConfig = Object.freeze({
  claim: Object.freeze({
    cooldownMinutes: 30,
    minimumGold: 300,
    maximumGold: 500,
  }),
  drop: Object.freeze({
    cooldownMinutes: 15,
    candidateCount: 3,
    selectionSeconds: 10,
    levelWeights: Object.freeze([
      Object.freeze({ level: 1, weight: 45 }),
      Object.freeze({ level: 2, weight: 28 }),
      Object.freeze({ level: 3, weight: 14 }),
      Object.freeze({ level: 4, weight: 8 }),
      Object.freeze({ level: 5, weight: 5 }),
    ]),
    rarityWeights: Object.freeze([
      Object.freeze({ rarityCode: "BASE", weight: 500_000 }),
      Object.freeze({ rarityCode: "COMMON", weight: 320_000 }),
      Object.freeze({ rarityCode: "UNCOMMON", weight: 160_000 }),
      Object.freeze({ rarityCode: "ALPHA", weight: 18_000 }),
      Object.freeze({ rarityCode: "ALL_STAR", weight: 1_900 }),
      Object.freeze({ rarityCode: "SUPERSTAR", weight: 95 }),
      Object.freeze({ rarityCode: "GOAT", weight: 5 }),
    ]),
  }),
  packs: Object.freeze([
    Object.freeze({
      packCode: "standard",
      displayName: "Standard Pack",
      default: true,
      priceGold: 1_000,
      cooldownSeconds: 1,
      cardCount: 1,
      levelWeights: Object.freeze([
        Object.freeze({ level: 1, weight: 45 }),
        Object.freeze({ level: 2, weight: 28 }),
        Object.freeze({ level: 3, weight: 14 }),
        Object.freeze({ level: 4, weight: 8 }),
        Object.freeze({ level: 5, weight: 5 }),
      ]),
      rarityWeights: Object.freeze([
        Object.freeze({ rarityCode: "BASE", weight: 100_000 }),
        Object.freeze({ rarityCode: "COMMON", weight: 350_000 }),
        Object.freeze({ rarityCode: "UNCOMMON", weight: 400_000 }),
        Object.freeze({ rarityCode: "ALPHA", weight: 120_000 }),
        Object.freeze({ rarityCode: "ALL_STAR", weight: 27_000 }),
        Object.freeze({ rarityCode: "SUPERSTAR", weight: 2_900 }),
        Object.freeze({ rarityCode: "GOAT", weight: 100 }),
      ]),
    }),
  ]),
  daily: Object.freeze({
    cooldownHours: 24,
    minimumGold: 1_500,
    maximumGold: 2_000,
    minimumShards: 20,
    maximumShards: 30,
  }),
  exchange: Object.freeze({
    shard: Object.freeze({
      levelUpCost: 500,
      levelUpQuantity: 1,
    }),
  }),
  trade: Object.freeze({
    maximumCardsPerPlayer: 10,
    maximumGoldPerPlayer: 20_000_000,
    expiryMinutes: 3,
  }),
  battle: Object.freeze({
    engineVersion: "2.0.0",
    rulesetVersion: "first-to-21-v1",
    configVersion: "battle-v2-playtest-1",
    aiCardLevel: 3,
    targetScore: 21,
    maximumPossessions: 200,
    threePointBaseProbability: 0.34,
    midRangeBaseProbability: 0.42,
    finishingBaseProbability: 0.60,
    ratingProbabilityScale: 0.004,
    minimumShotProbability: 0.20,
    maximumShotProbability: 0.85,
    turnoverBaseProbability: 0.08,
    turnoverRatingScale: 0.0025,
    offensiveReboundBaseProbability: 0.28,
    shotQualityModifiers: Object.freeze({
      OPEN: 0.08,
      LIGHTLY_CONTESTED: 0.02,
      CONTESTED: -0.06,
      HEAVILY_CONTESTED: -0.13,
    }),
  }),
  battlePlayback: Object.freeze({
    tickMilliseconds: 1_500,
    linesPerTick: 1,
    simulateButtonLifetimeMilliseconds: 60_000,
  }),
  quicksell: Object.freeze({
    shardRewards: Object.freeze({
      BASE: 1,
      COMMON: 2,
      UNCOMMON: 5,
      ALPHA: 30,
      ALL_STAR: 200,
      SUPERSTAR: 1_500,
      GOAT: 10_000,
    }),
  }),
  upgrade: Object.freeze({
    maximumCardLevel: 5,
    levelUpItemType: "LEVEL_UP",
    levelUpItemName: "Level Up",
  }),
});
