export const gameConfig = Object.freeze({
  claim: Object.freeze({
    cooldownMinutes: 15,
    maximumCharges: 2,
    minimumGold: 80,
    maximumGold: 120,
  }),
  drop: Object.freeze({
    cooldownMinutes: 15,
    maximumCharges: 2,
    candidateCount: 3,
    selectionSeconds: 20,
    levelWeights: Object.freeze([
      Object.freeze({ level: 1, weight: 45 }),
      Object.freeze({ level: 2, weight: 28 }),
      Object.freeze({ level: 3, weight: 14 }),
      Object.freeze({ level: 4, weight: 8 }),
      Object.freeze({ level: 5, weight: 5 }),
    ]),
    rarityWeights: Object.freeze([
      Object.freeze({ rarityCode: "BASE", weight: 5_249_534_570 }),
      Object.freeze({ rarityCode: "COMMON", weight: 3_201_050_400 }),
      Object.freeze({ rarityCode: "UNCOMMON", weight: 1_539_308_900 }),
      Object.freeze({ rarityCode: "ALPHA", weight: 7_513_200 }),
      Object.freeze({ rarityCode: "ALL_STAR", weight: 2_501_300 }),
      Object.freeze({ rarityCode: "SUPERSTAR", weight: 83_300 }),
      Object.freeze({ rarityCode: "GOAT", weight: 8_330 }),
    ]),
  }),
  packs: Object.freeze([
    Object.freeze({
      packCode: "standard",
      displayName: "Standard Pack",
      default: true,
      priceCurrency: "GOLD",
      priceAmount: 5_000,
      cooldownSeconds: 1,
      cardCount: 3,
      levelWeights: Object.freeze([
        Object.freeze({ level: 1, weight: 45 }),
        Object.freeze({ level: 2, weight: 28 }),
        Object.freeze({ level: 3, weight: 14 }),
        Object.freeze({ level: 4, weight: 8 }),
        Object.freeze({ level: 5, weight: 5 }),
      ]),
      rarityWeights: Object.freeze([
        Object.freeze({ rarityCode: "BASE", weight: 1_387_732_300 }),
        Object.freeze({ rarityCode: "COMMON", weight: 4_393_683_500 }),
        Object.freeze({ rarityCode: "UNCOMMON", weight: 3_805_361_800 }),
        Object.freeze({ rarityCode: "ALPHA", weight: 345_106_200 }),
        Object.freeze({ rarityCode: "ALL_STAR", weight: 67_116_100 }),
        Object.freeze({ rarityCode: "SUPERSTAR", weight: 833_400 }),
        Object.freeze({ rarityCode: "GOAT", weight: 166_700 }),
      ]),
    }),
    Object.freeze({
      packCode: "super",
      displayName: "Super Pack",
      priceCurrency: "SHARDS",
      priceAmount: 2_000,
      cooldownSeconds: 1,
      cardCount: 1,
      levelWeights: Object.freeze([
        Object.freeze({ level: 1, weight: 45 }),
        Object.freeze({ level: 2, weight: 28 }),
        Object.freeze({ level: 3, weight: 14 }),
        Object.freeze({ level: 4, weight: 8 }),
        Object.freeze({ level: 5, weight: 5 }),
      ]),
      rarityWeights: Object.freeze([
        Object.freeze({ rarityCode: "BASE", weight: 0 }),
        Object.freeze({ rarityCode: "COMMON", weight: 0 }),
        Object.freeze({ rarityCode: "UNCOMMON", weight: 0 }),
        Object.freeze({ rarityCode: "ALPHA", weight: 75_000_000 }),
        Object.freeze({ rarityCode: "ALL_STAR", weight: 24_153_846 }),
        Object.freeze({ rarityCode: "SUPERSTAR", weight: 769_231 }),
        Object.freeze({ rarityCode: "GOAT", weight: 76_923 }),
      ]),
    }),
  ]),
  daily: Object.freeze({
    cooldownHours: 24,
    xpReward: 300,
    minimumGold: 500_000,
    maximumGold: 500_000,
    minimumShards: 100_000,
    maximumShards: 100_000,
  }),
  weekly: Object.freeze({
    cooldownHours: 168,
    xpReward: 1_000,
    minimumGold: 3_000,
    maximumGold: 4_000,
    minimumShards: 200,
    maximumShards: 300,
  }),
  exchange: Object.freeze({
      maximumQuantity: 100,
      shard: Object.freeze({
      levelUpCost: 1_500,
      levelUpQuantity: 1,
    }),
  }),
  trade: Object.freeze({
    maximumCardsPerPlayer: 10,
    maximumGoldPerPlayer: 20_000_000,
    expiryMinutes: 3,
    reviewDelaySeconds: 5,
  }),
  battle: Object.freeze({
    engineVersion: "3.3.0",
    rulesetVersion: "first-to-21-player-tendencies-v1",
    configVersion: "battle-v3.2-player-tendencies-situational-traits-1",
    strategyResolverVersion: "battle-strategy-v4",
    traitResolverVersion: "battle-traits-v4",
    tendencyResolverVersion: "battle-tendencies-v2",
    aiMatchupCandidatePoolSize: 5,
    aiMatchupRatingTolerance: 8,
    targetScore: 21,
    maximumPossessions: 200,
    threePointBaseProbability: 0.34,
    threePointRatingBaseline: 75,
    threePointBelowBaselineScale: 0.0045,
    threePointAboveBaselineScale: 0.0055,
    minimumThreePointProbability: 0.08,
    maximumThreePointProbability: 0.70,
    midRangeBaseProbability: 0.42,
    finishingBaseProbability: 0.60,
    ratingProbabilityScale: 0.004,
    minimumShotProbability: 0.20,
    maximumShotProbability: 0.85,
    turnoverBaseProbability: 0.08,
    turnoverRatingScale: 0.0025,
    minimumTurnoverProbability: 0.03,
    maximumTurnoverProbability: 0.20,
    offensiveReboundBaseProbability: 0.28,
    fastBreakBaseProbability: 0.48,
    actionSelectionTemperature: 14,
    maximumActionChainLength: 5,
    actionHistoryLimit: 6,
    repetitionPenaltyAfter: 3,
    repetitionPenaltyMultiplier: 0.65,
    cooldownSeconds: 60 * 60,
      practice: Object.freeze({
        cooldownSeconds: 10,
      candidatePoolSize: 20,
      beamWidth: 100,
      rookiePowerThreshold: 67,
      rookieAiStatAdjustment: -6,
      streetPowerBands: Object.freeze([
        Object.freeze({ maximumPower: 67, powerOffset: -10 }),
        Object.freeze({ maximumPower: 75, powerOffset: -14 }),
        Object.freeze({ maximumPower: 1_000, powerOffset: -17 }),
      ]),
      bracketRules: Object.freeze([
        Object.freeze({
          code: "street",
          aiLevelDelta: -1,
          minimumAiLevel: 1,
          maximumAiLevel: 5,
          traitCapBasisPoints: 6_000,
          balancedAi: true,
        }),
        Object.freeze({
          code: "pro",
          aiLevelDelta: 0,
          minimumAiLevel: 1,
          maximumAiLevel: 5,
          powerOffset: -7,
          traitCapBasisPoints: 8_000,
          balancedAi: false,
        }),
        Object.freeze({
          code: "all-star",
          aiLevelDelta: 1,
          minimumAiLevel: 1,
          maximumAiLevel: 5,
          powerOffset: -3,
          traitCapBasisPoints: 9_500,
          balancedAi: false,
        }),
        Object.freeze({
          code: "legend",
          fixedAiLevel: 5,
          powerOffset: 2,
          traitCapBasisPoints: 12_000,
          balancedAi: false,
        }),
        ]),
      }),
      duel: Object.freeze({
        cooldownSeconds: 10,
        invitationSeconds: 60,
      }),
      winXp: 150,
    lossXp: 50,
    lossBaseGold: 250,
    lossPointGold: 15,
    winBaseGold: 950,
    winMarginGold: 45,
    streakBonusBasisPointsPerWin: Object.freeze({
      firstFive: 500,
      nextFive: 300,
      afterTen: 200,
    }),
    opponentBrackets: Object.freeze([
      Object.freeze({
        code: "street",
        displayName: "Street",
        minimumLineupStrength: 0,
        aiRatingOffset: -5,
        rewardMultiplierBasisPoints: 8_500,
      }),
        Object.freeze({
        code: "pro",
        displayName: "Pro",
        minimumLineupStrength: 70,
        aiRatingOffset: 0,
        rewardMultiplierBasisPoints: 10_000,
      }),
      Object.freeze({
        code: "all-star",
        displayName: "All-Star",
        minimumLineupStrength: 80,
        aiRatingOffset: 2,
        rewardMultiplierBasisPoints: 12_000,
      }),
      Object.freeze({
        code: "legend",
        displayName: "Legend",
        minimumLineupStrength: 88,
        aiRatingOffset: 4,
        rewardMultiplierBasisPoints: 14_000,
      }),
    ]),
    shotQualityModifiers: Object.freeze({
      OPEN: 0.08,
      LIGHTLY_CONTESTED: 0.02,
      CONTESTED: -0.06,
      HEAVILY_CONTESTED: -0.13,
    }),
  }),
  battlePlayback: Object.freeze({
    tickMilliseconds: 2_000,
    linesPerTick: 1,
    simulateButtonLifetimeMilliseconds: 60_000,
  }),
  quicksell: Object.freeze({
    rewards: Object.freeze({
        BASE: Object.freeze({ gold: 10, shards: 1 }),
        COMMON: Object.freeze({ gold: 20, shards: 2 }),
        UNCOMMON: Object.freeze({ gold: 40, shards: 4 }),
      ALPHA: Object.freeze({ gold: 250, shards: 30 }),
      ALL_STAR: Object.freeze({ gold: 7_000, shards: 350 }),
      SUPERSTAR: Object.freeze({ gold: 15_000, shards: 1_500 }),
      GOAT: Object.freeze({ gold: 50_000, shards: 10_000 }),
    }),
  }),
  upgrade: Object.freeze({
    maximumCardLevel: 5,
    levelUpItemType: "LEVEL_UP",
    levelUpItemName: "Level Up",
  }),
});
